version: '3'

services:
  db:
    image: postgres
    volumes:
        - /var/lib/postgresql
    command: "true"
  web:
    build: .
    command: python3 manage.py migrate --noinput;python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
