# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-05 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_added',
            field=models.DateField(null=True, verbose_name='Date added to the library'),
        ),
        migrations.AlterField(
            model_name='registerentry',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
