# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-04 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20190404_1304'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('action', models.CharField(max_length=6)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.Book')),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='books.Register')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.UserBorrower')),
            ],
        ),
        migrations.RemoveField(
            model_name='abstractregisterentry',
            name='book_borrowed',
        ),
        migrations.RemoveField(
            model_name='abstractregisterentry',
            name='register',
        ),
        migrations.RemoveField(
            model_name='abstractregisterentry',
            name='user',
        ),
        migrations.RemoveField(
            model_name='borrowerregisterentry',
            name='abstractregisterentry_ptr',
        ),
        migrations.RemoveField(
            model_name='returnregisterentry',
            name='abstractregisterentry_ptr',
        ),
        migrations.DeleteModel(
            name='AbstractRegisterEntry',
        ),
        migrations.DeleteModel(
            name='BorrowerRegisterEntry',
        ),
        migrations.DeleteModel(
            name='ReturnRegisterEntry',
        ),
    ]
