# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-12 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20190605_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='img',
            field=models.URLField(null=True),
        ),
    ]
