# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-04 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20190404_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerentry',
            name='register',
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
