# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-09-15 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_publication_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('code', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='isbn',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
