# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-09-15 06:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20190915_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='genre_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='books.Genre'),
        ),
    ]
