# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-04 14:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20190404_1626'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='AddressBorrower',
        ),
        migrations.RemoveField(
            model_name='userborrower',
            name='borrower',
        ),
        migrations.RemoveField(
            model_name='userborrower',
            name='user',
        ),
        migrations.AddField(
            model_name='book',
            name='acc',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='available_goodreads',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='sno',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='registerentry',
            name='borrower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Borrower'),
        ),
        migrations.AlterField(
            model_name='registerentry',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserBorrower',
        ),
    ]
