# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-04 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20190404_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_added',
            field=models.DateTimeField(null=True, verbose_name='Date added to the library'),
        ),
    ]
