# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-09-24 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20190915_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
