# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-04 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20190404_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerentry',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='books.Book'),
        ),
        migrations.AlterField(
            model_name='registerentry',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
