# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-10-26 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20190924_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='books.Publication'),
        ),
    ]
