# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-03 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20191026_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='person',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='borrower',
            name='pn',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
