# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-07 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20190407_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
