# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-07 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20190407_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtendLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_returndate', models.IntegerField(null=True)),
                ('original_returndate', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='registerentry',
            name='most_recent_extendlog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.ExtendLog'),
        ),
    ]
