# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-08 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20190407_2124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extendlog',
            name='current_returndate',
        ),
        migrations.RemoveField(
            model_name='extendlog',
            name='original_returndate',
        ),
        migrations.AddField(
            model_name='extendlog',
            name='new_returndate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='extendlog',
            name='returndate',
            field=models.DateTimeField(null=True),
        ),
    ]
