# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-09 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_auto_20190408_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='default',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='extendlog',
            name='entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.RegisterEntry'),
        ),
    ]
