# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-17 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_userjoinrequest_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='userjoinrequest',
            name='borrower',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.Borrower'),
        ),
    ]
